# CI/CD pipeline. 

name: CI/CD

on:
  pull_request:
  push:
    branches:
      - "main"
env:
  CI: true

jobs:
  build:
    name: Build .NET executable
    runs-on: ubuntu-latest
    container: ghul/devcontainer:dotnet
    timeout-minutes: 10

    steps:
    - uses: actions/checkout@v2

    - name: Show compiler version
      run: /usr/bin/ghul
                    
    - name: Publish
      run: dotnet publish

    - name: Upload .NET executable
      uses: actions/upload-artifact@v2
      with:
        name: executable-dotnet
        path: bin/Debug/net5.0/publish

  test:
    name: Test .NET executable under .NET Core
    needs: [build]
    runs-on: ubuntu-latest
    container: mcr.microsoft.com/dotnet/core/sdk:5.0
    timeout-minutes: 10

    steps:
    - uses: actions/checkout@v2

    - name: Download .NET executable
      uses: actions/download-artifact@v2
      with:
        name: executable-dotnet
        path: .

    - name: Run
      run: ./get-references
      
